#!/usr/bin/sh
#
# super simple script to check for arch updates

pkexec sh -c "yay -Sy"
archUpdatesNumber=$(yay -Qqu | wc -l)
archUpdatesPkg=$(yay -Qqu)

if [[ $archUpdatesNumber -gt 0 ]]; then
  notify-send "Updates Available" "Total: $archUpdatesNumber\n$archUpdatesPkg"
  echo "Updates Available"
  echo "Total: $archUpdatesNumber"
  echo $archUpdatesPkg
else
  notify-send "No Updates Available" ""
  echo "No Updates Available" ""
fi
