#!/usr/bin/env bash
#
# i3blocks blocklet script to monitor arch updates and aur
# Needs yay for AUR update check

#AURUPDATE_CMD=$(yay -Qqu | wc -l)
ARCHUPDATE_CMD=$(pacman -Qqu | wc -l)

#if [[ $AURUPDATE_CMD -gt 0 ]]; then
#    AURUPDATE=1
#    AURENDSTRING="AUR"
    #echo AUR updates avaiable.
#else
#    AURUPDATE=0
#fi

if [[ $ARCHUPDATE_CMD -gt 0 ]]; then
    ARCHUPDATE=1
    ARCHENDSTRING="SYS"
    #echo SYS updates avaiable.
else
    ARCHUPDATE=0  
fi

#if [ $AURUPDATE -eq 1 ] || [ $ARCHUPDATE -eq 1 ]; then
#    echo Updates: $ARCHENDSTRING $AURENDSTRING
#fi

if [ $ARCHUPDATE -eq 1 ]; then
    echo Updates: $ARCHENDSTRING
fi
