#!/bin/bash
#   Get's AUR pkgs.
#   More info at https://wiki.archlinux.org/title/Aurweb_RPC_interface

progname=$(basename $0)
# max results to show on search
export maxResults=25
# default download location
export downloadLocation=$(pwd)

function printHelp {
cat << EOF

   Usage: $progname -OPTIONS [package]

   Get's AUR pkgs.
   More info at https://wiki.archlinux.org/title/Aurweb_RPC_interface

   options :
     -h, --help         show this help message and exit
     -S, --search       searchs for keyword
     -r, --maxresults   max result on search, default is $maxResults
     -e, --exact        search for exact package
     -f, --searchfield  search with specific field. avaiable fields: "name" "name-desc" "maintainer" "depends" "makedepends" "optdepends" "checkdepends"
     -D, --download     download package
     -x, --extract      extract package when download is finished

EOF
}

# color support, thanks https://gist.github.com/elucify/c7ccfee9f13b42f11f81
RESTORE=$(echo -en '\033[0m')
RED=$(echo -en '\033[00;31m')
GREEN=$(echo -en '\033[00;32m')
YELLOW=$(echo -en '\033[00;33m')
BLUE=$(echo -en '\033[00;34m')
MAGENTA=$(echo -en '\033[00;35m')
PURPLE=$(echo -en '\033[00;35m')
CYAN=$(echo -en '\033[00;36m')
LIGHTGRAY=$(echo -en '\033[00;37m')
LRED=$(echo -en '\033[01;31m')
LGREEN=$(echo -en '\033[01;32m')
LYELLOW=$(echo -en '\033[01;33m')
LBLUE=$(echo -en '\033[01;34m')
LMAGENTA=$(echo -en '\033[01;35m')
LPURPLE=$(echo -en '\033[01;35m')
LCYAN=$(echo -en '\033[01;36m')
WHITE=$(echo -en '\033[01;37m')
BOLD=$(echo -en '\033[1m')

# check if dependencies are met
dependencies=("jq")
for pkg in ${dependencies[@]}; do
  checkDependency=$(pacman -Q $pkg)
  exitStatus=$?
  if [ "$exitStatus" -eq 1 ]; then
    echo ${BOLD}:: Error ! Please install $pkg ${RESTORE}
    exit 2
  fi
done



pkgString=""
#loops the argument string until is done
while [[ $# -gt 0 ]]; do
  key="$1"
  case "$key" in
    -h|--help) printHelp=1 ;;
    -S|--search) shift; pkgString="$1" ; searchPkg=1 ;;
    -D|--download) shift; pkgString="$1" ; downloadPkg=1 ;;
    -e|--exact) exactSearch=1 ;;
    -f|--searchfield) shift; searchField="$1" ;;
    -r|--maxresults) shift; maxResults="$1" ;;
    -x|--extract) extractPkg=1 ;;
    *) echo "Unknown option '$key'." ; printHelp ; exit 2 ;;
  esac
  shift
done

# doesnt work
# if no argument is given then
#if [[  $# -eq 1 ]]; then
  # full aur package detail
#  echo ${BOLD}:: Search AUR for $1 ${RESTORE}
#  resultJSON=$(curl -s "https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=$1")
#  nResult=$(echo $resultJSON | jq -r '.resultcount')
#  if [[ "$nResult" -eq 0 ]]; then
#    echo ${BOLD}:: Exact search return 0 results. Try $progname -S $1 ${RESTORE}
#    exit 2
#  else
#    echo $resultJSON | jq -r '.results[] | "ID:\t\t\(.ID) \nName:\t\t\(.Name) \nPackageBaseID:\t\(.PackageBaseID) \nPackageBase:\t\(.PackageBase) \nVersion:\t\(.Version) \nDescription:\t\(.Description) \nURL:\t\t\(.URL) \nNumVotes:\t\(.NumVotes) \nPopularity:\t\(.Popularity) \nOutOfDate:\t\(.OutOfDate) \nMaintainer:\t\(.Maintainer) \nFirstSubmitted:\t\(.FirstSubmitted) \nLastModified:\t\(.LastModified) \nURLPath:\t\(.URLPath) \nDepends:\t\(.Depends) \nMakeDepends:\t\(.MakeDepends) \nOptDepends:\t\(.OptDepends) \nLicense:\t\(.License) \nKeywords:\t\(.Keywords) "'
#    exit 0
#  fi
#fi


if [ "$printHelp" ]; then
  printHelp
  exit 0
fi

# if search and download flag are present then errors out
if [[ "$searchPkg" &&  "$downloadPkg" ]]; then
  echo ${RED}:: Search and download flags cant be used together, exiting...${RESTORE}
  exit 2
fi

# search package
if [ "$searchPkg" ]; then
  if [[ "$extractPkg" ]] ; then
    echo ${BOLD}:: -x, --extract does nothing with -S, --search flag, ignoring...${RESTORE}
  fi
  # start search
  # if exact search flag on
  if [[ "$exactSearch" ]] ; then
    echo ${BOLD}:: Search AUR for $pkgString ${RESTORE}
    if [ "$searchField" ]; then
      echo ${BOLD}:: -f, --searchfield flag does nothing with -e, --exact, ignoring...${RESTORE}
    fi
    resultJSON=$(curl -s "https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=$pkgString")
    nResult=$(echo $resultJSON | jq -r '.resultcount')
    if [[ "$nResult" -eq 0 ]]; then
      echo ${BOLD}:: Exact search return 0 results. Try $progname -S $pkgString ${RESTORE}
      exit 2
    else
      echo $resultJSON | jq -r '.results[] | "ID:\t\t\(.ID) \nName:\t\t\(.Name) \nPackageBaseID:\t\(.PackageBaseID) \nPackageBase:\t\(.PackageBase) \nVersion:\t\(.Version) \nDescription:\t\(.Description) \nURL:\t\t\(.URL) \nNumVotes:\t\(.NumVotes) \nPopularity:\t\(.Popularity) \nOutOfDate:\t\(.OutOfDate) \nMaintainer:\t\(.Maintainer) \nFirstSubmitted:\t\(.FirstSubmitted) \nLastModified:\t\(.LastModified) \nURLPath:\t\(.URLPath) \nDepends:\t\(.Depends) \nMakeDepends:\t\(.MakeDepends) \nOptDepends:\t\(.OptDepends) \nLicense:\t\(.License) \nKeywords:\t\(.Keywords) "'
      exit 0
    fi
  fi

  # if searchField flag is on
  if [ "$searchField" ]; then
    searchFieldOptions=("name" "name-desc" "maintainer" "depends" "makedepends" "optdepends" "checkdepends")
    for field in ${searchFieldOptions[@]}; do
      if [ "${field}" = "${searchField}" ]; then
        foundField=1
      fi
    done
    if [ "$foundField" ]; then
      echo ${BOLD}:: Search AUR for $pkgString with field "'$searchField'"${RESTORE}
      resultJSON=$(curl -s "https://aur.archlinux.org/rpc/?v=5&type=search&by=$searchField&arg=$pkgString")
      nResult=$(echo $resultJSON | jq -r '.resultcount')
      if [[ "$nResult" -gt $maxResults ]]; then
        echo ${BOLD}:: Please be more specific, $nResult packages found. Max result is set to $maxResults. Use -r, --maxresults to change it. ${RESTORE}
        exit 2
      fi
      echo ${BOLD}:: Found $nResult packages. ${RESTORE}
      echo $resultJSON | jq -r '.results[] | "Name:\t\t\(.Name) \nDescription:\t\(.Description)\n"'
      exit 0
    else
      echo ${BOLD}:: Search field "'$searchField'" is not valid. Valid options: ${RESTORE}
      echo ${BOLD}:: ${searchFieldOptions[*]} ${RESTORE}
      exit 2
    fi
  fi

  # normal search
  echo ${BOLD}:: Search AUR for $pkgString${RESTORE}
  resultJSON=$(curl -s "https://aur.archlinux.org/rpc/?v=5&type=search&arg=$pkgString")
  nResult=$(echo $resultJSON | jq -r '.resultcount')
  if [[ "$nResult" -gt $maxResults ]]; then
    echo ${BOLD}:: Please be more specific, $nResult packages found. Max result is set to $maxResults. Use -r, --maxresults to change it. ${RESTORE}
    exit 2
  else
    echo ${BOLD}:: Found $nResult packages. ${RESTORE}
    echo $resultJSON | jq -r '.results[] | "Name:\t\t\(.Name) \nDescription:\t\(.Description)\n"'
    exit 0
  fi
fi

# download package
# downloads the package, creates a folder with the pkg version
# if -x is on, extracts to it
if [ "$downloadPkg" ]; then
  if [[ "$exactSearch" ]] ; then
    echo ${BOLD}:: -e, --exact does nothing with -D, --download flag, ignoring...${RESTORE}
  fi
  if [ "$searchField" ]; then
    echo ${BOLD}:: -f, --searchfield flag does nothing with -D, --download ignoring...${RESTORE}
  fi
  resultJSON=$(curl -s "https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=$pkgString")
  nResult=$(echo $resultJSON | jq -r '.resultcount')
  if [[ "$nResult" -eq 1 ]]; then
    echo ${BOLD}:: Found $pkgString, downloading...${RESTORE}
    echo $resultJSON | jq -r '.results[] | "ID:\t\t\(.ID) \nName:\t\t\(.Name) \nPackageBaseID:\t\(.PackageBaseID) \nPackageBase:\t\(.PackageBase) \nVersion:\t\(.Version) \nDescription:\t\(.Description) \nURL:\t\t\(.URL) \nNumVotes:\t\(.NumVotes) \nPopularity:\t\(.Popularity) \nOutOfDate:\t\(.OutOfDate) \nMaintainer:\t\(.Maintainer) \nFirstSubmitted:\t\(.FirstSubmitted) \nLastModified:\t\(.LastModified) \nURLPath:\t\(.URLPath) \nDepends:\t\(.Depends) \nMakeDepends:\t\(.MakeDepends) \nOptDepends:\t\(.OptDepends) \nLicense:\t\(.License) \nKeywords:\t\(.Keywords) "'
    urlPath=$(echo $resultJSON | jq -r  .results[0].URLPath)
    curlURL=$(curl "https://aur.archlinux.org$urlPath" -o "$pkgString.tar.gz")
    curlURLExitStatus=$?
    if [ "$curlURLExitStatus" -eq 0 ]; then
      pkgVersion=$(echo $resultJSON | jq -r  .results[0].Version)
      mkdir -p $downloadLocation/$pkgString/$pkgVersion
      mv "$downloadLocation/$pkgString.tar.gz" "$downloadLocation/$pkgString/$pkgVersion"
      echo ${BOLD}:: Downloaded $pkgString to $downloadLocation/$pkgString/$pkgVersion ${RESTORE}
      if [ "$extractPkg" ]; then
        pkgLocation=$downloadLocation/$pkgString/$pkgVersion/$pkgString.tar.gz
        tar -xvf $pkgLocation -C $pkgString/$pkgVersion --strip-components=1
        echo ${BOLD}:: Extracted $pkgString to $downloadLocation/$pkgString/$pkgVersion ${RESTORE}
        exit 0
      fi
      exit 0
    else
      echo ${BOLD}:: Something went wrong ...${RESTORE}
      exit 2
    fi

  fi
fi
